### ISSUE TITLE
Prompt for removal of Manjaro wallpapers

### ISSUE THREAD

**Issue by andbenn** [sugkiy/ManjarotoArch#10]
Feature for a future version:  Prompt the user if they wish to remove the Manjaro wallpapers

I believe they are in the following package:

illyria-wallpaper

**Comment by sugkiy** [comment]
Ok that's a nice idea. I'll implement it as fast as I can.

**Comment by sugkiy** [comment]
What edition is it?

**Comment by andbenn** [comment]
That package was on my Manjaro XFCE and probably also on my Manjaro Budgie - I forgot to take notes.

As Manjaro could change the package name at some future point, I'd recommend checking if the wallpaper package is there, then a prompt to remove or keep.  And if no package, perhaps a notice that wallpapers weren't found.

Thanks a ton for making this script.  Used twice, with small errors and cleanup, but did learn a lot.

**Comment by sugkiy** [comment]
> Thanks a ton for making this script. I used it twice, with small errors and post cleanup, but did learn a lot.
Glad it helped. I tried to comment on every line of code to provide documentation. I can't really help with obvious hiccups, but I can help with small bugs.
