### ISSUE TITLE
grub entry is missing, it booted to memtest instead.

### ISSUE THREAD

**Issue by shikikan-neko08** [sugkiy/ManjarotoArch#14]
Description : Menu entry is missing and booted to Memtest instead         

Links :      
[Screenshot](https://twitter.com/Shikikan_Neko08/status/1444513642393731074)         
[Video](https://youtu.be/9VQhiOsT-B0)     

BIOS Mode  :  Legacy
VM               : VirtualBox 6.1.22     
OS                : Manjaro Pahvo 21.1.x

**Comment by sugkiy** [comment]
Thanks for the issue!

**Comment by sugkiy** [comment]
@shikikan-neko08 I fixed it with the latest commit. How about checking it out?

**Comment by shikikan-neko08** [comment]
Hmm ok,  i'll check it later

**Comment by sugkiy** [comment]
This is pretty amazing!
It fixed the LUKS issue as well!

**Comment by shikikan-neko08** [comment]
![Screenshot_2021-10-04_11-50-11](https://user-images.githubusercontent.com/54339576/135796388-f7bbcd24-0a6f-4ec0-ab60-b4610e95424d.png)
script is now working, tysm. gonna close this issue now.

**Comment by sugkiy** [comment]
Great! Thanks for testing on other machines!
