### ISSUE TITLE
Something broke 😕 

### ISSUE THREAD

**Issue by 416d72** [sugkiy/ManjarotoArch#7]
I used this yesterday, chose normal kernel 5.14, the same I was using in manjaro.
After reboot, I entered LUKS encryption password in grub screen, then it showed me `grub_disk_native_sectors not found`, and a grub rescue prompt!
After a bit of research I found no solution, so I decided to switch entirely to OpenSUSE tumbleweed (weird decision I know 😆 but I had no time).
This is just a feedback, with the hope that somebody finds a solution for people who might face the same problem.

**Comment by sugkiy** [comment]
Also do you have any information on what edition you use?

**Comment by 416d72** [comment]
I've already moved to opensuse, I don't know if those data would help you, but I'll post it here if it does, let me know please.

**Comment by sugkiy** [comment]
Then do you remember what edition(KDE, GNOME, etc...) you used?

**Comment by 416d72** [comment]
It was manjaro KDE.
IIRC, I had two partitions, one for efi and another LUKS encrypted for the rest including `/home`

**Comment by sugkiy** [comment]
Hmm.. I'll fire up a VM and see if one of the manjaro apps are related to disk encryption.

**Comment by sugkiy** [comment]
There are't any Manjaro apps relating to it, so I suspect the `pacman -Syyuu` caused `grub.cfg` to be screwed. Typing `refreshgrub` somehow fixed the issue partly, but the command is grubshell-specific so I think LUKS users should stay off from this.

**Comment by sugkiy** [comment]
I think #8 is related to this. Could you check this issue one more with the Git version using `make` and running `to_arch`?
