### ISSUE TITLE
After applying to Manjaro XFCE, subsequent boots have a "busy" mouse icon for 1 minute

### ISSUE THREAD

**Issue by andbenn** [sugkiy/ManjarotoArch#9]
After applying this script to a Manjaro XFCE instance, subsequent boots and logins have a weird effect of having a busy mouse cursor for 1 minute.

The mouse cursor gets a small spinning colored wheel in the bottom left.

I wonder if this is an issue with the whisker menu applet.  It's Manjaor logo disappeared, but it's blank.  I'm looking for an black backed Arch SVG file, but have a Tux in there for now.  Ideally the script would replace that whisker icon if possible.

Something may still be amiss, as attempts to change the whisker panel icon, takes about 20 seconds to show a picture chooser widget.  Granted, I had not thought about changing this before I used the to_arch script, so this might be as expected.

Still wondering what's driving the 1 minute busy mouse icon upon login though.

**Comment by sugkiy** [comment]
I have no idea what you're saying. And if you have multiple issues, could you please sort them into one metaissue since you're one user?
